# Generated by Django 4.0.6 on 2022-07-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=2, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
