# Generated by Django 4.0.6 on 2022-07-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='komentarz',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='nazwa',
        ),
    ]
